[package]
name = "libdlink"
version = "0.0.1"
edition = "2021"

authors = ["hehaoqian <39371646+hehaoqian@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/hehaoqian/libdlink/"
keywords = ["dlopen", "dylib", "shared"]

[dependencies]
